/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Show */

#ifndef _Included_Show
#define _Included_Show
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Show
 * Method:    showImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Show_showImage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
